/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-06-18 04:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import connection.DB;

public final class user_005fprediction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("connection.DB");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Catchy Carz a classified ads Category Flat Bootstrap\r\n");
      out.write("\tResponsive Website Template | Home :: w3layouts</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Catchy Carz Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"asset1/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"asset1/css/zoomslider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"asset1/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"asset1/css/component.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"asset1/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!--/web-fonts-->\r\n");
      out.write("<link\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Open+Sans:400,600,600italic,300,300italic,700,400italic'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Wallpoet' rel='stylesheet'\r\n");
      out.write("\ttype='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Ubuntu:400,500,700,300'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!--//web-fonts-->\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/* .tag1{\r\n");
      out.write("background-color: gold;\r\n");
      out.write("width: 170px;\r\n");
      out.write("padding-bottom: 15px;\r\n");
      out.write("margin-top:50px;\r\n");
      out.write("margin-left:540px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("margin-top:50px;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write(".tag1 a {\r\n");
      out.write("\tbackground-color: #199319;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 15px 25px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tag1 a:hover {\r\n");
      out.write("\tbackground-color: #22AA22;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");

String email = request.getParameter("email");
System.out.println("user_prediction.jsp_email:" + email);
String name = null;
String phone = null;

      out.write('\r');
      out.write('\n');

try{
 	
	 Connection con1=DB.getConnection();  
    Statement stmt1 = con1.createStatement();  
    ResultSet rs1 = stmt1.executeQuery("select * from uc where email ='"+email+"'");  
 
		while(rs1.next())
 		{
			name = rs1.getString("uname");
			phone = rs1.getString("pn");
       System.out.println("user_prediction.jsp"+ name+""+phone);
 		}
}catch(Exception e)
{
		System.out.println(e);
}


      out.write("\r\n");
      out.write("\t<!--/banner-section-->\r\n");
      out.write("\t<div id=\"demo-1\"\r\n");
      out.write("\t\tdata-zs-src='[\"asset1/images/2.jpg\", \"asset1/images/1.jpg\", \"asset1/images/3.jpg\"]'\r\n");
      out.write("\t\tdata-zs-overlay=\"dots\">\r\n");
      out.write("\t\t<div class=\"demo-inner-content\">\r\n");
      out.write("\t\t\t<div class=\"header-top\">\r\n");
      out.write("\t\t\t\t<!-- /header-left -->\r\n");
      out.write("\t\t\t\t<div class=\"header-left\">\r\n");
      out.write("\t\t\t\t\t<!-- /sidebar -->\r\n");
      out.write("\t\t\t\t\t<!-- <div id=\"sidebar\"> \r\n");
      out.write("\t\t\t\t\t\t     <h4 class=\"menu\">Menu</h4>\r\n");
      out.write("\t\t\t\t\t\t          <ul>\r\n");
      out.write("\t\t\t\t\t\t\t    <li><a href=\"upcoming.html\">New Cars <i class=\"glyphicon glyphicon-triangle-bottom\"> </i> </a>\r\n");
      out.write("\t\t\t\t\t\t\t      <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"find.html\"><span>Find New Cars</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"upcoming.html\"><span>Upcoming Cars</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"recommend.html\"><span>Recommend Me A Car</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"upcoming.html\"><span>New Launches</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"dealer.html\"><span>Locate Dealer</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li class=\"last\"><a href=\"price.html\"><span>On Road Price</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t   </ul>\r\n");
      out.write("\t\t\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t\t\t    <li><a href=\"compare.html\">Compare Cars</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t    <li><a href=\"cars.html\">Used Cars <i class=\"glyphicon glyphicon-triangle-bottom\"> </i></a>\r\n");
      out.write("\t\t\t\t\t\t\t      <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <li><a href=\"used.html\">Find Used cars</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li><a href=\"sell.html\">Sell Your Car</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li><a href=\"cars.html\"><span>Search Used Cars</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li class=\"last\"><a href=\"valuation.html\"><span>Used Car Valuation</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li><a href=\"dealer.html\"><span>Locate Dealer</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t\t\t   <li><a href=\"sell.html\">Sell Your Car</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t   <li><a href=\"news.html\">News And Reviews</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t   <li><a href=\"dealer.html\">Dealers And Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t   <li><a href=\"#\">More <i class=\"glyphicon glyphicon-triangle-bottom\"> </i> </a>\r\n");
      out.write("\t\t\t\t\t\t\t      <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"loan.html\"><span>Car Loan</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"codes.html\"><span>Short Codes</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"accessories.html\"><span>Car Accessories</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li><a href=\"tips.html\"><span>Tips and Advices</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <li class=\"last\"><a href=\"help.html\"><span>Privacy Policy</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t\t\t   <li><a href=\"insurance.html\">Insurance</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t <li><a href=\"app.html\">Catchy Carz app</a><li>\r\n");
      out.write("\t\t\t\t\t\t   </ul>\r\n");
      out.write("\t\t\t\t\t\t   <div id=\"sidebar-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t   <span></span>\r\n");
      out.write("\t\t\t\t\t\t\t   <span></span>\r\n");
      out.write("\t\t\t\t\t\t\t   <span></span>\r\n");
      out.write("\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t  var sidebarbtn = document.getElementById('sidebar-btn');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar sidebar = document.getElementById('sidebar');\r\n");
      out.write("\t\t\t\t\t\t\t\t   sidebarbtn.addEventListener('click', function () {\r\n");
      out.write("\t\t\t\t\t\t\t\t  if(sidebar.classList.contains('visible')){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsidebar.classList.remove('visible'); \r\n");
      out.write("\t\t\t\t\t\t\t\t   }else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsidebar.className = 'visible';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t  });\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<!-- //sidebar -->\r\n");
      out.write("\t\t\t\t\t<!--   <div class=\"tag\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal2\"><span class=\"glyphicon glyphicon-log-in\"></span> Sign Up</a></div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //header-left -->\r\n");
      out.write("\t\t\t\t<!--    <div class=\"search-box\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sb-search\" class=\"sb-search\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"name\" class=\"sb-search-input\" placeholder=\"Enter your search term...\" type=\"search\" id=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"sb-search-submit\" type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sb-icon-search\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\tsearch-scripts\r\n");
      out.write("\t\t\t\t\t\t<script src=\"asset1/js/classie.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script src=\"asset1/js/uisearch.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\tnew UISearch( document.getElementById( 'sb-search' ) );\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t//search-scripts\r\n");
      out.write("\t\t\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal4\"><i class=\"glyphicon glyphicon-map-marker\" aria-hidden=\"true\"></i>Select Your Location</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><button id=\"showRight\" class=\"navig\">Login </button>\r\n");
      out.write("\t\t\t\t\t\t\t <div class=\"cbp-spmenu-push\">\r\n");
      out.write("\t\t\t\t\t\t\t<nav class=\"cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right\" id=\"cbp-spmenu-s2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Login</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" class=\"email\" placeholder=\"Email\" required=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"password\" placeholder=\"Password\" required=\"\"/>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand\"><span></span> Remember me</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Forgot password?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"LOGIN\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icons\"></span><span class=\"text\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"twt\"><a href=\"#\"><span class=\"icons\"></span><span class=\"text\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"ggp\"><a href=\"#\"><span class=\"icons\"></span><span class=\"text\">Google+</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul> \r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<script src=\"asset1/js/classie2.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tvar menuRight = document.getElementById( 'cbp-spmenu-s2' ),\r\n");
      out.write("\t\t\t\t\t\t\t\tshowRight = document.getElementById( 'showRight' ),\r\n");
      out.write("\t\t\t\t\t\t\t\tbody = document.body;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tshowRight.onclick = function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tclassie.toggle( this, 'active' );\r\n");
      out.write("\t\t\t\t\t\t\t\tclassie.toggle( menuRight, 'cbp-spmenu-open' );\r\n");
      out.write("\t\t\t\t\t\t\t\tdisableOther( 'showRight' );\r\n");
      out.write("\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction disableOther( button ) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif( button !== 'showRight' ) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclassie.toggle( showRight, 'disabled' );\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\tNavigation from Right To Left\r\n");
      out.write("\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<!--banner-info-->\r\n");
      out.write("\t\t\t<div class=\"banner-info\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\">FIND <span class=\"logo-sub\">ACCIDENT</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t<span>COME LOOK </span> <span>AT THE SELECTION! </span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<p>Eye it â try it â Find it!</p>\r\n");
      out.write("\t\t\t\t<div class=\"tag1\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal1\"><span></span>\r\n");
      out.write("\t\t\t\t\t\tClick Here To Find Â» </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--  <form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search-two\">\r\n");
      out.write("\t\t\t\t\t<select id=\"country\" onchange=\"change_country(this.value)\" class=\"frm-field required\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"null\"><img src=\"asset1/images/rupee.png\" alt=\" \" class=\"img-responsive\" />Brands</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"abt\">ABT</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ac\">AC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"amc\">AMC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"amg\">AMG</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"abarth\">Abarth</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"acura\">Acura</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"alfa romeo\">Alfa Romeo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"arial\">Ariel</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"armstrong siddeley\">Armstrong Siddeley</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ascari\">Ascari</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"aston martin\">Aston Martin</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"audi\">Audi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"austin\">Austin</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bac\">BAC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bmw\">BMW</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"byd\">BYD</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bentley\">Bentley</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bertone\">Bertone</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"brilliance\">Brilliance</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bristol\">Bristol</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bufori\">Bufori</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bugatti\">Bugatti</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"buick\">Buick</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"caddilac\">Caddilac</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"caparo\">Caparo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"carbon motors\">Carbon Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"caterham\">Caterham</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"cheri\">Cheri</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"chevrolet\">Chevrolet</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"chrysler\">Chrysler</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"citroen\">CitroÃ«n</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"continental\">Continental</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"dacia\">Dacia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daewoo\">Daewoo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daihatsu\">Daihatsu</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daimler\">Daimler</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"datsun\">Datsun</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"de lorean\">De Lorean</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"de tomaso\">De Tomaso</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"dodge\">Dodge</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"eagle\">Eagle</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ferrari\">Ferrari</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"fiat\">Fiat</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Fisker</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"force\">Force</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ford\">Ford</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gmc\">GMC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">GTA Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"geely\">Geely</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"general motors\">General Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ghia\">Ghia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ginetta\">Ginetta</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gumpert\">Gumpert</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hsv\">HSV</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"healey\">Healey</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hennessey motors\">Hennessey Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"holden\">Holden</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"honda\">Honda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hummer\">Hummer</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hyundai\">Hyundai</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"infinity\">Infinty</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"isuzu\">Isuzu</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"italdesign\">Italdesign</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jaguar\">Jaguar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jeep\">Jeep</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jensen motors\">Jensen Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"kia motors\">Kia Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"koenig\">Koeing</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"koenigsegg\">Koenigsegg</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lada\">Lada</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lamborghini\">Lamborghini</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lancia\">Lancia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"land rover\">Land Rover</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lexus\">Lexus</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lincoln\">Lincoln</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lotus\">Lotus</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"marussia\">Marussia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mclaren\">McLaren</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mgb\">MG Motor</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mini\">MINI</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mahindra\">Mahindra</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"maruti suzuki\">Maruti Suzuki</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"maserati\">Maserati</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"maybach\">Maybach</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mazda\">Mazda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mercedes-benz\">Mercedes-Benz</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mercury\">Mercury</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mitsubishi\">Mitsubishi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"morgan\">Morgan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mosler\">Mosler</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"nsu\">NSU</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"noble\">Noble</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"nissan\">Nissan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"oldsmobile\">Oldsmobile</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"opel\">Opel</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"packard\">Packard</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"pagani\">Pagani</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"panoz\">Panoz</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"peugeot\">Peugeot</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"plymouth\">Plymouth</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"pontiac\">Pontiac</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"porsche\">Porsche</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"proton\">Proton</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ram\">RAM</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ruf automobile\">RUF Automobile</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"radical\">Radical</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"reliant\">Reliant</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"renault\">Renault</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"rimac\">Rimac</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"rinspeed\">Rinspeed</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"rolls royce\">Rolls Royce</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"rover\">Rover</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"srt\">SRT</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ssc\">SSC</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"saab\">SAAB</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"saleen\">Saleen</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"saturn\">Saturn</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"scion\">Scion</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"seat\">SEAT</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"shelby\">Shelby</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"skoda\">Å koda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"smart\">Smart</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"spyker\">Spyker</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ssangyong\">Ssangyong</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"studebaker\">Studebaker</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"subaru\">Subaru</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"sunbeam\">Sunbeam</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"suzuki\">Suzuki</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"tata motors\">TATA Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"tvr\">TVR</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"tesla\">Tesla</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"toyota\">Toyota</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"triumph\">Triumph</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"vauxhall\">Vauxhall</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Vector\">Vector</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"venturi\">Venturi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"volkswagen\">Volkswagen</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"volvo\">Volvo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"w motors\">W Motors</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"webasto\">Webasto</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"zagato\">Zagato</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"zenos\">Zenos</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"zenvo\">Zenvo</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section_room\">\r\n");
      out.write("\t\t\t\t\t<select id=\"country\" onchange=\"change_country(this.value)\" class=\"frm-field required\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"null\"><img src=\"asset1/images/rupee.png\" alt=\" \" class=\"img-responsive\" /> Budget</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"null\">0</option>     \r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">10,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">12,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">13,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">15,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">17,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">21,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">22,000</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"AX\">25,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">32,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">34,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">36,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">38,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">40,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">42,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">44,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">36,000</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AX\">50,000</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Find Car\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<!--//banner-info-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- discounts-->\r\n");
      out.write("\t<div class=\"modal ab fade\" id=\"myModal1\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog about\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content about\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close ab\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"discount\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Accident & Prediction</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Enter your location</p>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"country12\" onchange=\"updatePinCode(this.value)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"frm-field required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected=\"selected\" value=\"-1\">-Select-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600040\">100 Feet Road, AnnaNagar,Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600034\">Nungambakkam, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600002\">Mount Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600017\">T Nagar, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600096\">Rajiv Gandhi Salai, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600005\">Kamarajar Salai, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600040\">Thirumangalam, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600016\">GST Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600084\">Poonamallee High Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600116\">Porur, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600042\">Velachery Main Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600097\">OMR, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600044\">Chromepet, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600096\">Outer Ring Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600078\">Old Mahabalipuram Road, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600060\">Tambaram, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600041\">ECR, Chennai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"600032\">Alandur, Chennai</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select><br> <input type=\"text\" id=\"pinCodeInput\" name=\"pin code\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"Pin code\" placeholder=\"Pin code\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body about\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"dis-contact\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Contact Information</h4>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"Prediction\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" value=\"");
      out.print(name );
      out.write("\" class=\"name active\" placeholder=\"Name\" required=\"\" readonly> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" value=\"");
      out.print(email );
      out.write("\" class=\"email\" placeholder=\"Email\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"phone\" value=\"");
      out.print(phone);
      out.write("\"class=\"phone\" placeholder=\"Phone\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"loc\" type=\"hidden\" name=\"location\" value=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-c\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"checkbox1\"> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"\" checked=\"\" required=\"required\"><i> </i>I agree to\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTerms and Conditions.</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Find\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //discounts-->\r\n");
      out.write("\t<!-- //sign-up-->\r\n");
      out.write("\t<div class=\"modal ab fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog sign\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content about\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header one\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close sg\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"discount one\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Sign Up</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body about\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-top sign-top one\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"name active\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Name\" required=\"\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"email \" class=\"email\" placeholder=\"Email\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Password\" required=\"\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" id=\"brand1\" value=\"\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"brand1\"><span></span> Remember me?</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-bottom one\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Forgot password?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"SIGN UP\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"social-icons\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icons\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"twt\"><a href=\"#\"><span class=\"icons\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ggp\"><a href=\"#\"><span class=\"icons\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">Google+</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //sign-up-->\r\n");
      out.write("\t<!-- /location-->\r\n");
      out.write("\t<div class=\"modal ab fade\" id=\"myModal4\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog sign\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content about\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header one\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close sg\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"discount one\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Please Tell Us Your City</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body about\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-top sign-top location\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"country12\" onchange=\"change_country(this.value)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"frm-field required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"null\">Select City</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Amsterdam</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Bahrain</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Cannes</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Dublin</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Edinburgh</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Florence</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Georgia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Hungary</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Hong Kong</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Johannesburg</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Kiev</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"city\">Others...</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //location-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t<!-- //Services -->\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"asset1/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"asset1/js/jquery.zoomslider.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t $(window).load(function() {\t\t\t\r\n");
      out.write("\t\t\t\t  $(\"#flexiselDemo\").flexisel({\r\n");
      out.write("\t\t\t\t\tvisibleItems:1,\r\n");
      out.write("\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\tautoPlaySpeed:1000,    \t\t\r\n");
      out.write("\t\t\t\t\tpauseOnHover:true,\r\n");
      out.write("\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t $(window).load(function() {\t\t\t\r\n");
      out.write("\t\t\t\t  $(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("\t\t\t\t\tvisibleItems: 4,\r\n");
      out.write("\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\tpauseOnHover:true,\r\n");
      out.write("\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\tvisibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"asset1/js/jquery.flexisel.js\"></script>\r\n");
      out.write("\t<script src=\"asset1/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write(" function updatePinCode(selectedValue) {\r\n");
      out.write("     var pinCodeInput = document.getElementById('pinCodeInput');\r\n");
      out.write("     var loc = document.getElementById('loc');\r\n");
      out.write("     pinCodeInput.value = selectedValue;\r\n");
      out.write("     loc.value = selectedValue;\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
