/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-06-18 04:40:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>USER HOME</title>\r\n");
      out.write("<!-- Meta-Tags -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Smart Career Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //Meta-Tags -->\r\n");
      out.write("<link href=\"asset2/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /><!--bootstrap-css-->\r\n");
      out.write("<link href=\"asset2/css/font-awesome.css\" rel=\"stylesheet\"> <!--font-awesome-css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"asset2/css/flexslider.css\" type=\"text/css\" media=\"screen\" /><!--flexslider-css-->\r\n");
      out.write("<link href=\"asset2/css/circles.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /><!--skill-circles-->\r\n");
      out.write("<link href=\"asset2/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /><!--style-sheet-->\r\n");
      out.write("<link href='css/aos.css' rel='stylesheet prefetch' type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--fonts-->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Cabin:400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<!--//fonts-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String email = request.getParameter("p");


      out.write("\r\n");
      out.write("<!--banner start here-->\r\n");
      out.write("<div class=\"banner\" id=\"home\">\r\n");
      out.write("<div class=\"agileinfo-dot\">\r\n");
      out.write("   <div class=\"header\">\r\n");
      out.write("\t\t   <div class=\"header-main\">\r\n");
      out.write("\t\t\t<!--  <div class=\"header-top-agileits\">\r\n");
      out.write("\t\t   \t <div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"w3l-social\" data-aos=\"fade-right\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"agile_forms\" data-aos=\"fade-left\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"active\" href=\"#\" data-toggle=\"modal\" data-target=\"#myModal2\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i> Login</a> </li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal3\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Register</a> </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t   \t <div class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h1><a  href=\"index.jsp\">USER</a></h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- navbar-header -->\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse cl-effect-13\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\" class=\"active\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"\" onclick=\"reg()\">REGISTER</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"\" onclick=\"req()\">REQUIREMENTS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"\" onclick=\"predict()\">PREDICTION</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"\" onclick=\"down()\">DOWNLOAD</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\" class=\"\">LOGOUT</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write(" function reg(){\r\n");
      out.write("\t var email = '");
      out.print( email);
      out.write("';\r\n");
      out.write("\t console.log(email);\r\n");
      out.write("\t/* var email = document.getElementById(\"hai2\").value; */\r\n");
      out.write("\twindow.location.replace(\"user_reg.jsp?email=\"+email);\r\n");
      out.write(" }\r\n");
      out.write(" function req(){\r\n");
      out.write("\t var email = '");
      out.print( email);
      out.write("';\r\n");
      out.write("\t console.log(email);\r\n");
      out.write("\t/* var email = document.getElementById(\"hai2\").value; */\r\n");
      out.write("\twindow.location.replace(\"user_req.jsp?email=\"+email);\r\n");
      out.write(" }\r\n");
      out.write(" function predict(){\r\n");
      out.write("\t var email = '");
      out.print( email);
      out.write("';\r\n");
      out.write("\t window.location.replace(\"user_prediction.jsp?email=\"+email);\r\n");
      out.write(" }\r\n");
      out.write(" function down(){\r\n");
      out.write("\t var email = '");
      out.print( email);
      out.write("';\r\n");
      out.write("\t window.location.replace(\"user_rp_down.jsp?email=\"+email);\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3ls_search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cd-main-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"cd-header-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"cd-search-trigger\" href=\"#cd-search\"> <span></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul> <!-- cd-header-buttons -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"cd-search\" class=\"cd-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"Search\" type=\"search\" placeholder=\"Click enter after typing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\t\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\t   <div class=\"banner-bottom\">\r\n");
      out.write("\t\t   \t   <section class=\"slider\">\r\n");
      out.write("\t\t\t\t <div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t  <li>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"banner-bottom-text\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t<h3>Knowledge is power, and knowledge about road safety can save lives</h3>\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  <li>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"banner-bottom-text\">\r\n");
      out.write("\t\t\t\t\t  \t\t<h3>The future of road safety is in data-driven prediction.</h3>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  <li>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"banner-bottom-text\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t<h3>Let's use technology to make our roads safer</h3>\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  <li>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"banner-bottom-text\">\r\n");
      out.write("\t\t\t\t\t  \t\t<h3>No more lives lost to preventable accidents</h3>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t  </li>\t\t\t  \r\n");
      out.write("\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t      </section>\r\n");
      out.write("\t\t\t<div class=\"thim-click-to-bottom\">\r\n");
      out.write("\t\t\t\t<a href=\"#about\" class=\"scroll\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-chevron-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--banner end here-->\r\n");
      out.write("\t<!-- Modal2 -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"signin-form profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"agileinfo_sign\">Login</h3>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"login-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"E-mail\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"tp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"login-social-grids\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal3\" > Don't have an account?</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- //Modal2 -->\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Modal3 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal fade\" id=\"myModal3\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"signin-form profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"agileinfo_sign\">Register</h3>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"login-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   <input type=\"text\" name=\"name\" placeholder=\"Username\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"Email\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Confirm Password\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Register\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\"> By clicking register, I agree to your terms</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t<!-- //Modal3 -->\r\n");
      out.write("<!--banner bottom-->\r\n");
      out.write("<div class=\"banner-btm-w3layouts\" id=\"about\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"tittle-agileinfo\">\r\n");
      out.write("\t\t<span>01</span>\r\n");
      out.write("\t\t<h2>Real-Time Accident Risk Assessment</h2>\r\n");
      out.write("\t\t<p ></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"about-main\">\r\n");
      out.write("\t\t<div class=\"col-md-4 about-grids\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-bookmark-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t<h3 class=\"subheading-agileits-w3layouts\">Data-Driven Predictions</h3>\r\n");
      out.write("\t\t\t<p class=\"para-agileits-w3layouts\">Our prediction model is built on vast datasets and employs sophisticated algorithms to analyze historical accident patterns and various influencing factors</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4 about-grids\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-handshake-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t<h3 class=\"subheading-agileits-w3layouts\">Accident Hotspot Mapping</h3>\r\n");
      out.write("\t\t\t<p class=\"para-agileits-w3layouts\">This map empowers communities and authorities to take targeted action to prevent accidents and enhance road safety.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4 about-grids\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-money\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t<h3 class=\"subheading-agileits-w3layouts\">Collaborative Data Sharing</h3>\r\n");
      out.write("\t\t\t<p class=\"para-agileits-w3layouts\">We believe that data-driven safety measures require collaboration among various stakeholders.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--//banner bottom-->\r\n");
      out.write("\r\n");
      out.write("<!--services -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- //services -->\r\n");
      out.write("<!-- Team -->\r\n");
      out.write("<div class=\"team\" id=\"team\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"tittle-agileinfo\">\r\n");
      out.write("\t\t\t<span>02</span>\r\n");
      out.write("\t\t\t<h3>Our marvellous team</h3>\r\n");
      out.write("\t\t\t<p ></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"agile_team_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agile_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-sixth\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"asset2/images/t1.jpg\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Agnese brent</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"w3l-social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agile_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-sixth\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"asset2/images/t2.jpg\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Richard Walsh</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"w3l-social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agile_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-sixth\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"asset2/images/t3.jpg\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Lisa ortiz</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"w3l-social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 agile_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-sixth\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"asset2/images/t4.jpg\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Scott flores</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"w3l-social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Team -->\r\n");
      out.write("<!-- Stats -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"w3ls_agile_circle_progress agile_info_shadow\" id=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cir_agile_info \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"skill-grids\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"skills-grid text-center\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"circle\" id=\"circles-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>A percentage of individual cases that we take yearly, on average.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"skills-grid text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"circle\" id=\"circles-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>A share of commercial/business cases that we process yearly</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"skills-grid text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"circle\" id=\"circles-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>The number of returning customers, over the period of last 10 years</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"skills-grid text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"circle\" id=\"circles-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>A percentage of individual cases that we take yearly, on average.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write(" -->\r\n");
      out.write("\t<!-- //Stats -->\r\n");
      out.write("\r\n");
      out.write("<!-- gallery -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- //gallery --> \r\n");
      out.write("\r\n");
      out.write("<!-- testimonials -->\r\n");
      out.write("\t<div class=\"testimonials\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"tittle-agileinfo\">\r\n");
      out.write("\t\t\t<span>03</span>\r\n");
      out.write("\t\t\t<h3>Customers feedback</h3>\r\n");
      out.write("\t\t\t<p ></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3_testimonials_grids\">\r\n");
      out.write("\t\t\t\t<div id=\"slideshow\" class=\"disabled\">\r\n");
      out.write("\t\t\t\t\t<button class=\"previous\"><b>« Previous</b></button>\r\n");
      out.write("\t\t\t\t\t<button class=\"next\"><b>Next »</b></button>\r\n");
      out.write("\t\t\t\t\t<div class=\"strip\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slide sticky\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 agileinfo_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"agileinfo_team_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-top-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"asset2/images/t1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test-right-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6>Federica</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-bottom-w3-agile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"para-agileits-w3layouts\">Road accident prediction websites can help to save lives by providing drivers with information about the risk of accidents in their area.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 agileinfo_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"agileinfo_team_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-top-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"asset2/images/t2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test-right-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6>Liza Brent</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-bottom-w3-agile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"para-agileits-w3layouts\">Road accident prediction websites are a valuable tool for law enforcement agencies and city planners who can use the information to identify high-risk areas and implement safety measures.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 agileinfo_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"agileinfo_team_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-top-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"asset2/images/t3.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test-right-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6>Leslie gross</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-bottom-w3-agile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"para-agileits-w3layouts\">Road accident prediction websites can help drivers to make informed decisions about when and where to travel, and how to drive safely.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 agileinfo_team_grid\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"agileinfo_team_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-top-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"asset2/images/t4.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test-right-wthree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h6>Kimberly Barker</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-bottom-w3-agile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"para-agileits-w3layouts\">Road accident prediction websites are a relatively new technology, but they have the potential to make a significant impact on road safety.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //testimonials -->\r\n");
      out.write("<!-- newsletter -->\r\n");
      out.write("\r\n");
      out.write("<!-- //newsletter -->\r\n");
      out.write("<!-- map -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- //map -->\r\n");
      out.write("\r\n");
      out.write("<!-- contact -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- //contact -->\r\n");
      out.write("\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"asset2/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<!--search-bar-->\r\n");
      out.write("\t\t<script src=\"asset2/js/main.js\"></script>\t\r\n");
      out.write("<!--//search-bar-->\r\n");
      out.write("<!-- FlexSlider -->\r\n");
      out.write("\t\t\t\t  <script defer src=\"asset2/js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t\t\t\t  <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t$(function(){\t\t\t\t \r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t\t\t  $('.flexslider').flexslider({\r\n");
      out.write("\t\t\t\t\t\tanimation: \"slide\",\r\n");
      out.write("\t\t\t\t\t\tstart: function(slider){\r\n");
      out.write("\t\t\t\t\t\t  $('body').removeClass('loading');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t  });\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t  </script>\r\n");
      out.write("<!-- FlexSlider -->\r\n");
      out.write("<!-- clients-slider-script -->\r\n");
      out.write("\t\t\t\t<script src=\"asset2/js/slideshow.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"asset2/js/launcher.js\"></script>\r\n");
      out.write("<!-- //clients-slider-script -->\r\n");
      out.write("<!-- /circle-->\r\n");
      out.write("\t <script type=\"text/javascript\" src=\"asset2/js/circles.js\"></script>\r\n");
      out.write("\t\t\t\t\t         <script>\r\n");
      out.write("\t\t\t\t\t\t\t\tvar colors = [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t['#ffffff', '#fd9426'], ['#ffffff', '#fc3158'],['#ffffff', '#53d769'], ['#ffffff', '#147efb']\r\n");
      out.write("\t\t\t\t\t\t\t\t\t];\r\n");
      out.write("\t\t\t\t\t\t\t\tfor (var i = 1; i <= 7; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar child = document.getElementById('circles-' + i),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpercentage = 30 + (i * 10);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCircles.create({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid:         child.id,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpercentage: percentage,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tradius:     80,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth:      10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnumber:   \tpercentage / 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext:       '%',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcolors:     colors[i - 1]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t<!-- //circle -->\r\n");
      out.write("\t<!-- for-Map -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar menu_ul = $('.faq > li > ul'),\r\n");
      out.write("\t\t\t\t\t   menu_a  = $('.faq > li > a');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmenu_ul.hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tmenu_a.click(function(e) {\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tif(!$(this).hasClass('active')) {\r\n");
      out.write("\t\t\t\t\t\tmenu_a.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\tmenu_ul.filter(':visible').slideUp('normal');\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass('active').next().stop(true,true).slideDown('normal');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(this).removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t$(this).next().stop(true,true).slideUp('normal');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!-- //for-Map -->\r\n");
      out.write("<script src=\"asset2/js/jzBox.js\"></script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"asset2/js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"asset2/js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<!-- smooth scrolling -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t\tvar defaults = {\r\n");
      out.write("\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t*/\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- Animation-effect -->\r\n");
      out.write("<script src='js/aos.js'></script>\r\n");
      out.write("<script src=\"asset2/js/aosindex.js\"></script>\r\n");
      out.write("<!-- //Animation-effect -->\r\n");
      out.write("\t<a href=\"#home\" class=\"scroll\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n");
      out.write("<!-- //smooth scrolling -->\r\n");
      out.write("<script src=\"asset2/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
